version: '3'
services:
  # Apache
  www:
    image: manchenkoff/server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./src:/var/www
